version: '3.7'
services:
  dwpf-backend:
    container_name: dwpf-backend
    image: cr.yandex/crp5td2ej9d9m9e880v2/football:0.95
    ports:
      - "443:443"
    restart: always
    depends_on:
      - fluentbit
    volumes:
      - /var/lib/database2:/var/lib/database2
    entrypoint:
      -
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: app.logs
  fluentbit:
    container_name: fluentbit
    image: cr.yandex/yc/fluent-bit-plugin-yandex:v1.0.3-fluent-bit-1.8.6
    ports:
      - 24224:24224
      - 24224:24224/udp
    restart: always
    environment:
      YC_GROUP_ID: e23cnpqdu2squinnqbkv
    volumes:
      - /etc/fluentbit/fluentbit.conf:/fluent-bit/etc/fluent-bit.conf
      - /etc/fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf
